from shape_keys_plus.panels.shape_keys_plus import DATA_PT_shape_keys_plus as ShapeKeysPlus
from shape_keys_plus.panels.shape_key_driver import DATA_PT_skp_shape_key_driver as ShapeKeyDriver
from shape_keys_plus.panels.shape_key_icon import DATA_PT_skp_shape_key_icon as ShapeKeyIcon
from shape_keys_plus.panels.copy_customization import DATA_PT_skp_copy_customization as CopyCustomization
